Add reusable workflows on DEV
Cerebellum-Network/explorer pull request #38
Opened 2022-11-16 13:16 UTC by DmitriyMolch

2022-11-16 13:42 UTC, krolol approved these changes

2022-11-16 14:08 UTC, krolol requested changes

2022-11-16 14:08 UTC, krolol commented on .github/workflows/prod.yaml
> +      NETWORK_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_NETWORK_AWS_ACCESS_KEY_ID }}
Need to change to PROD secrets

2022-11-16 14:08 UTC, krolol commented on .github/workflows/stage.yaml
> +      NETWORK_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_NETWORK_AWS_ACCESS_KEY_ID }}
Need to change to STAGE secrets

2022-11-16 14:54 UTC, DmitriyMolch commented on .github/workflows/prod.yaml
> +      NETWORK_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_NETWORK_AWS_ACCESS_KEY_ID }}
Fixed

2022-11-16 14:54 UTC, DmitriyMolch commented on .github/workflows/stage.yaml
> +      NETWORK_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_NETWORK_AWS_ACCESS_KEY_ID }}
Fixed

2022-11-16 23:29 UTC, AndreiNavoichyk approved these changes

2022-11-17 07:42 UTC, krolol approved these changes

2022-11-17 08:06 UTC, merged